apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: june19-rhoai
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: june19-rhoai
  name: june19-rhoai
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
