apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: june19-rhoai
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: june19-rhoai
  name: june19-rhoai
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: june19-rhoai
    weight: 100
  wildcardPolicy: None
